# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
    
    config.ssh.insert_key = false
  
    config.vm.define "ans" do |ans|
      ans.vm.box = "shekeriev/centos-8-minimal"
      ans.vm.hostname = "ans.dob.lab"
      ans.vm.network "private_network", ip: "192.168.98.99"
      ans.vm.synced_folder "vagrant/", "/vagrant"
      ans.vm.provision "shell", inline: <<EOS
sudo dnf install -y epel-release
sudo dnf install -y ansible
EOS
  end
  
  config.vm.define "web" do |web|
    web.vm.box = "shekeriev/ubuntu-20-04-server"
    web.vm.hostname = "web-dob"
    web.vm.network "private_network", ip: "192.168.98.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080
    web.vm.synced_folder "web/", "/web"
  end
   
  config.vm.define "db" do |db|
    db.vm.box = "shekeriev/centos-8-minimal"
    db.vm.hostname = "db-dob"
    db.vm.network "private_network", ip: "192.168.98.101"
    db.vm.synced_folder "db/", "/db"
  end
end