- hosts: webservers
  become: true

  tasks:
    - name: Install Apache HTTP Server
      apt: name=apache2 state=present
    
    - name: Start Apache HTTP Server and Enable it
      service: name=apache2 state=started enabled=true
    - name: Install php
      apt:
        pkg:
        - php
        - libapache2-mod-php
    - name: Install firewalld
      apt: name=firewalld

    - name: Allow HTTP service in the firewall
      firewalld: service=http state=enabled permanent=yes immediate=yes
- hosts: dbservers
  become: true

  tasks:
    - name: Install MariaDB Server
      dnf: name=mariadb,mariadb-server state=present
    - name: Start and enable MariaDB
      service: name=mariadb state=started enabled=true
